AWSTemplateFormatVersion: "2010-09-09"
#Author : "Samir H. Elbehiry"
Description: ECR repo test 
Resources:
  AWSTestTestRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "npr/nginx"
Outputs:
  AWSTestTestArn:
    Value: !GetAtt AWSTestTestRepo.Arn
    Export:
      Name: AWSTestTestArn